<a href="https://colab.research.google.com/github/MJ199999/SW-Project/blob/master/text_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 7.2 MB/s 
     |████████████████████████████████| 6.6 MB 58.1 MB/s 
     |████████████████████████████████| 120 kB 78.7 MB/s 


In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers import GPT2LMHeadModel, AutoModel

import time
import argparse

def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate a text"
    )
    parser.add_argument(
        "",
        type=str,
        default=None,
        help="Path to pretrained model or model identifier from huggingface.co/models.",
    )
    parser.add_argument(
        "--prompt_text",
        type=str,
        default="함께",
        help="Prompting text",
    )

    # Sanity checks
    if args.model_name_or_path is None:
        raise ValueError("Need model name or path.")

    return args


def main():
    args = parse_args()

    model_path = args.model_name_or_path
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = AutoModelForCausalLM.from_pretrained(model_path)
    text = args.prompt_text
    input_ids = tokenizer.encode(text)
    # Check generation time
    start = time.time() 
    gen_ids = model.generate(torch.tensor([input_ids]),
                            max_length=1024,
                            repetition_penalty=2.0,
                            pad_token_id=tokenizer.pad_token_id,
                            eos_token_id=tokenizer.eos_token_id,
                            bos_token_id=tokenizer.bos_token_id,
                            # num_beams=5,
                            do_sample=True,
                            top_k=30, 
                            top_p=0.95,
                            use_cache=True)
    generated_text = tokenizer.decode(gen_ids[0,:].tolist())
    end = time.time()
    
    print(generated_text)
    print(f"{end - start:.5f} sec")


if __name__ == '__main__':
    main()

In [ ]:
from transformers import TFAutoModelForCausalLM

model = TFAutoModelForCausalLM.from_pretrained("/gdrive/MyDrive/Colab Notebooks/sw-project/SW-Project/skt-ko-gpt-trinity-1.2B-v0.5-2")

All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at /gdrive/MyDrive/Colab Notebooks/sw-project/SW-Project/skt-ko-gpt-trinity-1.2B-v0.5-2.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [ ]:
max_key_len = 5

In [ ]:
from transformers import AutoTokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

tokenizer = AutoTokenizer.from_pretrained("skt/ko-gpt-trinity-1.2B-v0.5", bos_token='</s>', eos_token='</s>', pad_token='<pad>')
keyword = "사랑"

bos_token = [tokenizer.bos_token]
eos_token = [tokenizer.eos_token]

tokens = bos_token + tokenizer.tokenize(keyword) + eos_token
input_id = tokenizer.convert_tokens_to_ids(tokens)
input_id = pad_sequences([input_id], maxlen=max_key_len, value=tokenizer.pad_token_id, padding='post')[0]

input_id = np.array(input_id, dtype=int)

In [ ]:
input_id

array([    1, 30716,     1,     3,     3])

In [ ]:
input_ids1 = tokenizer(keyword, return_tensors='pt').input_ids

In [ ]:
input_ids1

tensor([[30716]])

In [ ]:
input_ids1.unsqueeze(0)

tensor([[[30716]]])

In [ ]:
gen_id = model.generate(input_ids1, do_sample=False, max_length=200, repetition_penalty=2.0)
gen_text = tokenizer.batch_decode(gen_id, skip_special_tokens=True)

In [ ]:
gen_text

['사랑시그이다.\n다면눈고 바 불러나의\n들 눈다.바저 \n그리 바다에에 이름을나는동그는.\n랴오는억신의다가부한\t 만나가지지 와서에게오세 싶다.\n르르 않는푸기 그의월은을넓저리스떨그러우리하리는들은만울 그하나누나밤보 있다.\n흐라.\n노 끝 바다 싶다. 나무날올깨려 없는여개 그대 있는인칠 어둠비물 너깔교']